/** Every Phosphor icon, generated by `extension/build.mjs`. */
declare module 'virtual:atoms-icons' {
  import type { ComponentType } from 'react';
  const icons: Record<string, ComponentType<Record<string, unknown>>>;
  export = icons;
}
