import type { ComponentExamplesData } from '@/src/types/docs';

/**
 * Docs + MCP data for `Filter`. Read by `scripts/generate.ts` and served
 * through the MCP `get_component` tool and the docs site.
 */
export const data: ComponentExamplesData = {
  name: 'Filter',
  category: 'Inputs',
  tagline:
    'Two-column faceted filter panel: a rail of categories beside the options for the active one.',
  props: [
    {
      name: 'groups',
      type: 'readonly FilterGroup[]',
      default: '—',
      description:
        'Categories down the rail, in order. Each supplies either `options` (a searchable checkbox list) or `content` (a pane of its own).',
    },
    {
      name: 'value',
      type: 'Record<string, readonly string[]>',
      default: '—',
      description:
        'Selected option values keyed by group id. Supplying it makes the panel controlled. Groups with nothing selected are absent from the map.',
    },
    {
      name: 'defaultValue',
      type: 'Record<string, readonly string[]>',
      default: '{}',
      description: 'Initial selection when the panel is uncontrolled.',
    },
    {
      name: 'onChange',
      type: '(value: FilterValue) => void',
      default: '—',
      description:
        'Fires with the whole next selection, not a delta, so it drops straight into a query.',
    },
    {
      name: 'activeGroupId',
      type: 'string',
      default: '—',
      description:
        'Active category. Supplying it makes the rail controlled; the search box clears whenever it moves.',
    },
    {
      name: 'defaultActiveGroupId',
      type: 'string',
      default: "groups[0].id",
      description: 'Initially active category when the rail is uncontrolled.',
    },
    {
      name: 'onActiveGroupChange',
      type: '(groupId: string) => void',
      default: '—',
      description: 'Fires when the rail selection moves.',
    },
    {
      name: 'onClearAll',
      type: '() => void',
      default: '—',
      description:
        'Fires after `Clear all filter`, alongside `onChange` with the empty selection. Use it to reset `content` groups, whose state the panel does not hold.',
    },
    {
      name: 'title',
      type: 'string',
      default: "'Filter'",
      description: 'Heading in the top bar.',
    },
    {
      name: 'labels',
      type: '{ clearAll?, selectAll?, clearGroup?, noResults? }',
      default: '—',
      description:
        'Overrides for the four strings the panel writes itself, for translation or house wording.',
    },
    {
      name: 'anchorEl',
      type: 'HTMLElement | null',
      default: '—',
      description:
        'Anchors the panel in a popover against this element. Without it the panel renders in flow and `open` / `onClose` are ignored.',
    },
    {
      name: 'open',
      type: 'boolean',
      default: 'false',
      description: 'Whether the popover is showing. Only read with `anchorEl`.',
    },
    {
      name: 'onClose',
      type: '(event, reason) => void',
      default: '—',
      description:
        'Fires on backdrop click or Escape. Only read with `anchorEl`.',
    },
    {
      name: 'anchorOrigin',
      type: '{ vertical, horizontal }',
      default: "{ vertical: 'bottom', horizontal: 'left' }",
      description: 'Which point of the anchor the panel hangs from.',
    },
    {
      name: 'transformOrigin',
      type: '{ vertical, horizontal }',
      default: "{ vertical: 'top', horizontal: 'left' }",
      description:
        'Which corner of the panel meets that point, and the corner the open animation grows out of. Use `horizontal: \'right\'` for a trigger at the right end of a toolbar — left-aligned there, the panel leaves the viewport and gets pushed back in.',
    },
  ],
  examples: [
    {
      title: 'Faceted filter',
      description:
        'One entry per category. A group needs nothing but `id`, `label`, and its options — the rail badge, the search box, and the bulk actions come with it.',
      code: [
        'const groups = [',
        "  { id: 'entity', label: 'Entity', options: entityOptions },",
        "  { id: 'assignee', label: 'Assignee', options: assigneeOptions },",
        "  { id: 'vendor', label: 'Vendor Name', options: vendorOptions },",
        '];',
        '',
        '<Filter groups={groups} value={selection} onChange={setSelection} />',
      ].join('\n'),
    },
    {
      title: 'Anchored to a button',
      description:
        'Passing `anchorEl` floats the panel under a control instead of rendering it in flow. The trigger carries the count: `countActiveFilters` sums the same numbers the rail shows, so the closed button and the open panel always agree — and unlike summing `value` by hand it also counts groups that declare their own `count`.',
      code: [
        'const activeCount = countActiveFilters(groups, selection);',
        '',
        '<Button',
        '  variant="secondary"',
        '  appearance="outline"',
        '  startIcon={<FadersHorizontalIcon />}',
        '  onClick={(event) => setAnchorEl(event.currentTarget)}',
        '>',
        '  Filter',
        '  {activeCount > 0 && (',
        '    <Chip size="sm" variant="primary" component="span" label={activeCount} />',
        '  )}',
        '</Button>',
        '',
        '<Filter',
        '  groups={groups}',
        '  value={selection}',
        '  onChange={setSelection}',
        '  anchorEl={anchorEl}',
        '  open={anchorEl !== null}',
        '  onClose={() => setAnchorEl(null)}',
        '/>',
      ].join('\n'),
    },
    {
      title: 'Filtering a data grid',
      description:
        'What the panel is mostly for. A search box and a badged trigger sit above the grid; `Clear Filters` resets both, because from the reader\'s side there is one filtered table, not two. The rows are narrowed here rather than through the grid\'s own filter model — the panel already produces the selection, and translating it into MUI X\'s filter items would only hide what is happening.',
      code: [
        'const activeCount = countActiveFilters(groups, selection);',
        'const query = search.trim().toLowerCase();',
        '',
        'const rows = QUERY_ROWS.filter(',
        '  (row) =>',
        "    (query === '' || rowSearchText(row).includes(query)) &&",
        '    groups.every((group) =>',
        '      matchesFacet(row, group.id, selection[group.id] ?? [])',
        '    )',
        ');',
        '',
        '<Stack direction="row" justifyContent="space-between">',
        '  <TextField',
        '    placeholder="Search..."',
        '    value={search}',
        '    onChange={(event) => setSearch(event.target.value)}',
        '    startAdornment={<MagnifyingGlassIcon />}',
        '  />',
        '  <Stack direction="row" spacing={1}>',
        '    <Button',
        '      variant="secondary"',
        '      appearance="outline"',
        '      disabled={!isFiltered}',
        '      onClick={handleClearFilters}',
        '    >',
        '      Clear Filters',
        '    </Button>',
        '    <Button',
        '      variant="secondary"',
        '      appearance="outline"',
        '      startIcon={<FadersHorizontalIcon />}',
        '      onClick={(event) => setAnchorEl(event.currentTarget)}',
        '    >',
        '      Filter',
        '      {activeCount > 0 && (',
        '        <Chip size="sm" variant="primary" component="span" label={activeCount} />',
        '      )}',
        '    </Button>',
        '  </Stack>',
        '</Stack>',
        '',
        '<DataGrid size="sm" rows={rows} columns={QUERY_COLUMNS} />',
        '',
        '<Filter',
        '  groups={groups}',
        '  value={selection}',
        '  onChange={setSelection}',
        '  anchorEl={anchorEl}',
        '  open={anchorEl !== null}',
        '  onClose={() => setAnchorEl(null)}',
        "  anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}",
        "  transformOrigin={{ vertical: 'top', horizontal: 'right' }}",
        '/>',
      ].join('\n'),
    },
    {
      title: 'Chips as option labels',
      description:
        'An option label can be any node. Give those rows a `searchText` — a node has no text for the search box to read, so without it the row drops out as soon as anything is typed.',
      code: [
        'const statusOptions = [',
        '  {',
        "    value: 'routed',",
        '    label: <Chip size="sm" variant="warning" label="Routed to Human" />,',
        "    searchText: 'Routed to Human',",
        '  },',
        '  {',
        "    value: 'answered',",
        '    label: <Chip size="sm" variant="success" label="Auto-answered" />,',
        "    searchText: 'Auto-answered',",
        '  },',
        '];',
      ].join('\n'),
    },
    {
      title: 'A category with its own pane',
      description:
        'Supply `content` instead of `options` when the category is not a multi-select. The group then owns its state: report how much is active through `count`, and reset it from `onClearAll`.',
      code: [
        '<Filter',
        '  groups={[',
        '    {',
        "      id: 'range',",
        "      label: 'Date Range',",
        "      count: preset === 'all' ? 0 : 1,",
        '      content: <DateRangePane value={preset} onChange={setPreset} />,',
        '    },',
        '    ...groups,',
        '  ]}',
        '  value={selection}',
        '  onChange={setSelection}',
        "  onClearAll={() => setPreset('all')}",
        '/>',
      ].join('\n'),
    },
    {
      title: 'A short, fixed list',
      description:
        'Four options need neither a search box nor bulk actions — both are more chrome than help at that length.',
      code: [
        '{',
        "  id: 'type',",
        "  label: 'Type',",
        '  options: typeOptions,',
        '  disableSearch: true,',
        '  disableBulkActions: true,',
        '}',
      ].join('\n'),
    },
    {
      title: 'House wording',
      description:
        'The four strings the panel writes itself are the only copy it owns.',
      code: [
        '<Filter',
        '  groups={groups}',
        '  title="Refine"',
        '  labels={{',
        "    clearAll: 'Reset',",
        "    selectAll: 'Select visible',",
        "    clearGroup: 'Clear',",
        "    noResults: 'Nothing matches that',",
        '  }}',
        '/>',
      ].join('\n'),
    },
  ],
  dos: [
    'Use the option `value` your query already uses, not the display text — `onChange` hands the map straight back to you',
    'Give every node label a `searchText` so the row survives a search',
    'Set `count` on a `content` group, and reset that group from `onClearAll`',
    'Keep the search box on any list long enough to scroll — `disableSearch` is for short, fixed ones',
    'Anchor the panel with `anchorEl` when it opens from a toolbar button',
    "Move `anchorOrigin` and `transformOrigin` to `horizontal: 'right'` for a trigger at the right of a toolbar, so the panel neither runs off the page nor grows from a corner that is not touching it",
    'Badge the trigger with `countActiveFilters(groups, value)` so the count survives the panel closing',
    'Pair the panel with a free-text search box over the grid — the two answer different questions, and one `Clear Filters` should reset both',
  ],
  donts: [
    "Don't supply both `options` and `content` on one group — `content` wins and the options are never drawn",
    "Don't expect `Select all` to reach rows a search has hidden; it and `Clear all` both act on what is visible",
    "Don't treat an absent group key as different from an empty one — a cleared group leaves the map entirely",
    "Don't put a single-choice category in `options` — a checkbox list says multi-select; use `content` with a `Radio` group",
    "Don't stretch the panel to the page width; it is sized for a rail of categories, not a full-page form",
  ],
  relatedComponents: ['DataGrid', 'Chip', 'Checkbox', 'TextField'],
};
